# definir el puerto
server:
  port: 8084

# -- Application Configuration --
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
            # File URI - Adjust path according to your system:
            # Windows: file:///C:/Users/YourUser/microservices-lab1/config-repo
            uri: file://D:/TodoAprendizaje/CursoFullStackJavaTECSUP/ClasesGrabadas/5-SpringProfesional/config-repo
            # Git Configuration
            default-label: main
            search-paths:
              - .